# Generated by Django 5.0.6 on 2024-06-25 13:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("track", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BannedTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banned_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("banned_until", models.IntegerField()),
                (
                    "track",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banned",
                        to="track.music",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RandBTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banned_until", models.IntegerField(blank=True, null=True)),
                ("banned_at", models.DateTimeField(blank=True, null=True)),
                ("report_count", models.IntegerField(blank=True, default=0)),
                (
                    "track",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="track",
                        to="track.music",
                    ),
                ),
            ],
            options={
                "db_table": "report_banned_tracks",
            },
        ),
        migrations.CreateModel(
            name="ReportTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reported_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("description", models.TextField()),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reported",
                        to="track.music",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_track",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
